---
name: 'Documentation'

on:
  push:

permissions:
  contents: read

jobs:
  build-upload-docs:
    name: Build and upload docs
    runs-on: ubuntu-22.04
    steps:
      - run: which pip
      - run: pip list
